#! /usr/bin/env python3

from urllib.parse import urlencode
from urllib.request import Request, urlopen, HTTPDigestAuthHandler, build_opener, install_opener
import sys
import json
from os import path

config = json.load(open(path.expanduser('~/.config/magnets.json')))
tix_host = config['host']
tix_url = tix_host + '/transfers/action'

username = config['user']
password = config['password']

auth_handler = HTTPDigestAuthHandler()
auth_handler.add_password(realm='Tixati Web Interface',
        uri=tix_host, user=username,
        passwd=password)

opener = build_opener(auth_handler)
# ...and install it globally so it can be used with urlopen.
install_opener(opener)

for line in sys.stdin:
    post_fields = {
            'addlinktext': line.strip(),
            "addlink": "Add",
            }     # Set POST fields here

    request = Request(url = tix_url, data = urlencode(post_fields).encode(), method = 'POST')
    json = urlopen(request).read().decode()
    print(json)
